version: '2'
services:
    ywclub:
        image: "wordpress:nginx"
        build:
            context: .
            dockerfile: Dockerfile.nginx
        volumes:
            - ${Web_Directory}:/usr/share/nginx/html/
        networks:
            - frontend
        depends_on:
            - php
        env_file: 
            - .env
    php:
        image: "wordpress:php"
        build:
            context: .
            dockerfile: Dockerfile.php
        volumes:
            - ${Web_Directory}:/usr/share/nginx/html/
        networks:
            - frontend
            - backend
        environment:
            MYSQL_PASSWORD: root
        depends_on:
            - mysql
        env_file: 
            - .env
    mysql:
        image: "wordpress:mariadb"
        build:
            context: .
            dockerfile: Dockerfile.mariadb
        volumes:
            - mysqldata:/var/lib/mysql
            - ${Web_Directory}:/usr/share/nginx/html/
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ywclub
            MYSQL_USER: ywclub
            MYSQL_PASSWORD: ywclub
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
volumes:
    mysqldata:
networks:
    frontend:
    backend:
